//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VrpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGAN_ETS_BANCAIRE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORGAN_ETS_BANCAIRE()
        {
            this.VRP_RELATION_ETS = new HashSet<VRP_RELATION_ETS>();
        }
    
        public string BANQUE_CODE_BCEAO { get; set; }
        public string CODE_ORG { get; set; }
        public string NOM { get; set; }
        public string PRENOMS { get; set; }
        public string ETCIV_MATRICULE { get; set; }
        public string E_MAIL1 { get; set; }
        public string E_MAIL2 { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string ADR_POST1 { get; set; }
        public string ADR_POST2 { get; set; }
        public string ADR_GEO1 { get; set; }
        public string ADR_GEO2 { get; set; }
        public Nullable<System.DateTime> DATE_CREATION { get; set; }
        public Nullable<System.DateTime> DATE_MODIF { get; set; }
    
        public virtual ETS_BANCAIRE ETS_BANCAIRE { get; set; }
        public virtual ORGANIGRAMME ORGANIGRAMME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VRP_RELATION_ETS> VRP_RELATION_ETS { get; set; }
    }
}
