//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VrpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANIGRAMME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORGANIGRAMME()
        {
            this.ORGAN_ETS_BANCAIRE = new HashSet<ORGAN_ETS_BANCAIRE>();
        }
    
        public string CODE_ORG { get; set; }
        public string LIBELLE { get; set; }
        public string NIVEAU { get; set; }
        public string HIERARCHIE { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORGAN_ETS_BANCAIRE> ORGAN_ETS_BANCAIRE { get; set; }
    }
}
